#!/bin/bash
set -e
cd /home/user/saidadencoder222/toolkit-outreach
source venv/bin/activate

NICHES=(
  "meal prep coach"
  "personal trainer online"
  "macro coach"
  "bodybuilding coach"
  "diet coach"
  "womens fitness coach"
  "online fitness coach"
  "calisthenics coach"
  "yoga instructor business"
  "crossfit coach business"
  "day trading coach"
  "forex trading coach"
  "options trading coach"
  "crypto trading coach"
  "stock trading coach"
  "swing trading coach"
  "trading mentor"
  "futures trading coach"
  "personal finance coach"
  "budgeting coach"
  "wealth coach"
  "dropshipping coach"
  "amazon fba coach"
  "ecommerce coach"
  "print on demand coach"
  "shopify coach"
  "tiktok shop coach"
  "online store coach"
  "social media marketing coach"
  "content creation coach"
  "email marketing coach"
  "digital marketing coach"
  "youtube automation coach"
  "personal branding coach"
  "content strategy coach"
  "influencer marketing coach"
  "ugc creator coach"
  "real estate investing coach"
  "real estate wholesaling coach"
  "airbnb hosting coach"
  "house flipping coach"
  "business coach"
  "side hustle coach"
  "online coaching business"
  "freelancing coach"
  "consulting business coach"
  "coaching business mentor"
  "productivity coach"
  "mindset coach business"
  "entrepreneur coach"
)

for n in "${NICHES[@]}"; do
  echo "=== $n ==="
  python3 main.py find-leads --query "$n" --max 25 || echo "(failed, continuing)"
done
